export default function Head(): JSX.Element {
  return (
    <>
      <title> Gabriel Nascimento </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="👋" />
    </>
  );
  
}

export const metadata = {
  title: 'Portifólio | Gabriel Nascimento',
  description: 'Meu portifólio',
};